name: happy plus one
 
on:
  push:
    branches:
      - main
  schedule:  
    - cron:  23 23 * * *   #国际标准时间，北京时间+8
 
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout codes'
        uses: actions/checkout@v2
      - name: 'set up python'
        uses: actions/setup-python@v2
        with:
         python-version: ${{ matrix.python-version }}
      - name: requirements
        run: |
         python -m pip install --upgrade pip
         
      - name: 'Epic/steam happy +1'
         run: |
          python ${{ github.workspace }}/happy_plus_one.py ${{ secrets.PUSHPLUS_TOKEN }}  #你的PUSHPLUS TOKEN
